### ISSUE TITLE
No images in preview

### ISSUE THREAD

**Issue by lenntt** [timonwong/OmniMarkupPreviewer#104]
This issue was introduced recently on my machine, it used to work for me, not sure component causes this. But when I preview a markdown page using this plugin, I don't see any embedded pictures.

The stacktrace sublime (dev build 3123) gives me is (looks related):

```
AttributeError: 'module' object has no attribute 'parse'
Traceback (most recent call last):
  File "/home/lennart/.config/sublime-text-3/Packages/OmniMarkupPreviewer/OmniMarkupLib/libs/bottle.py", line 764, in _handle
    return route.call(**args)
  File "/home/lennart/.config/sublime-text-3/Packages/OmniMarkupPreviewer/OmniMarkupLib/libs/bottle.py", line 1575, in wrapper
    rv = callback(*a, **ka)
  File "/home/lennart/.config/sublime-text-3/Packages/OmniMarkupPreviewer/OmniMarkupLib/Server.py", line 95, in handler_public
    return get_static_public_file(filepath)
  File "/home/lennart/.config/sublime-text-3/Packages/OmniMarkupPreviewer/OmniMarkupLib/Server.py", line 88, in get_static_public_file
    return static_file(filepath, root=DEFAULT_STATIC_FILES_DIR)
  File "/home/lennart/.config/sublime-text-3/Packages/OmniMarkupPreviewer/OmniMarkupLib/libs/bottle.py", line 2084, in static_file
    mimetype, encoding = mimetypes.guess_type(filename)
  File "./python3.3/mimetypes.py", line 288, in guess_type
  File "./python3.3/mimetypes.py", line 114, in guess_type
```

**Comment by lenntt** [comment]
I think the CSS is affected by this as well.
