### ISSUE TITLE
Unable preview markdown file in web browser.

### ISSUE THREAD

**Issue by tosone** [timonwong/OmniMarkupPreviewer#124]
Sublime Text Version: 3143

Console output:
OmniMarkupPreviewer: [INFO] Launching web browser for http://127.0.0.1:20000/view/25
OmniMarkupPreviewer: [ERROR] Exception occured while rendering using MarkdownRenderer
  Traceback (most recent call last):
    File "/Users/tosone/Library/Application Support/Sublime Text 3/Packages/OmniMarkupPreviewer/OmniMarkupLib/RendererManager.py", line 266, in render_text
    rendered_text = renderer.render(text, filename=filename)
    File "/Users/tosone/Library/Application Support/Sublime Text 3/Packages/OmniMarkupPreviewer/OmniMarkupLib/Renderers/MarkdownRenderer.py", line 48, in render
    extensions=self.extensions)
    File "/Users/tosone/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3/markdown/__init__.py", line 493, in markdown
    md = Markdown(*args, **kwargs)
    File "/Users/tosone/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3/markdown/__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
    File "/Users/tosone/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3/markdown/__init__.py", line 185, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
    File "/Users/tosone/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3/markdown/__init__.py", line 291, in build_extension
    return module.makeExtension(**configs)
    File "/Users/tosone/Library/Application Support/Sublime Text 3/Packages/OmniMarkupPreviewer/OmniMarkupLib/Renderers/libs/mdx_strikeout.py", line 17, in makeExtension
    return StrikeoutExtension(configs=configs)
    File "/Users/tosone/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3/markdown/extensions/__init__.py", line 51, in __init__
    self.setConfigs(kwargs)
    File "/Users/tosone/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3/markdown/extensions/__init__.py", line 82, in setConfigs
    self.setConfig(key, value)
    File "/Users/tosone/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3/markdown/extensions/__init__.py", line 70, in setConfig
    if isinstance(self.config[key][0], bool):
  KeyError: 'configs'

**Comment by asfaltboy** [comment]
Seems like an issue with the strikeout extension and a fix was suggested in ticket #85 , in [this comment][1].

This can probably be closed as duplicate...

[1]: https://github.com/timonwong/OmniMarkupPreviewer/issues/85#issuecomment-168078270
