### ISSUE TITLE
'buffer_id(235) is not valid (closed or unsupported file format)'

### ISSUE THREAD

**Issue by travelliu** [timonwong/OmniMarkupPreviewer#125]
Error: 404 Not Found

Sorry, the requested URL 'http://127.0.0.1:51004/view/235' caused an error:

'buffer_id(235) is not valid (closed or unsupported file format)'

**NOTE:** If you run multiple instances of Sublime Text, you may want to adjust
the `server_port` option in order to get this plugin work again.

OmniMarkupPreviewer: [INFO] Launching web browser for http://127.0.0.1:51004/view/235
OmniMarkupPreviewer: [ERROR] Exception occured while rendering using MarkdownRenderer
  Traceback (most recent call last):
    File "/Users/Travel/Library/Application Support/Sublime Text 3/Packages/OmniMarkupPreviewer/OmniMarkupLib/RendererManager.py", line 266, in render_text
    rendered_text = renderer.render(text, filename=filename)
    File "/Users/Travel/Library/Application Support/Sublime Text 3/Packages/OmniMarkupPreviewer/OmniMarkupLib/Renderers/MarkdownRenderer.py", line 48, in render
    extensions=self.extensions)
    File "/Users/Travel/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3/markdown/__init__.py", line 493, in markdown
    md = Markdown(*args, **kwargs)
    File "/Users/Travel/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3/markdown/__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
    File "/Users/Travel/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3/markdown/__init__.py", line 185, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
    File "/Users/Travel/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3/markdown/__init__.py", line 291, in build_extension
    return module.makeExtension(**configs)
    File "/Users/Travel/Library/Application Support/Sublime Text 3/Packages/OmniMarkupPreviewer/OmniMarkupLib/Renderers/libs/mdx_superscript.py", line 43, in makeExtension
    return SuperscriptExtension(configs=configs)
    File "/Users/Travel/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3/markdown/extensions/__init__.py", line 51, in __init__
    self.setConfigs(kwargs)
    File "/Users/Travel/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3/markdown/extensions/__init__.py", line 82, in setConfigs
    self.setConfig(key, value)
    File "/Users/Travel/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3/markdown/extensions/__init__.py", line 70, in setConfig
    if isinstance(self.config[key][0], bool):
  KeyError: 'configs'

**Comment by asfaltboy** [comment]
I'm getting the exact same error when trying to preview a markdown file, and to add, the RST renders completely fine.

I'm using Sublime Text 3 (build 3143) on MacOS High Sierra 10.13.3 (17D102) and latest OmniMarkupPreviewer from package control

**Comment by asfaltboy** [comment]
Just noticed this seems like an issue with the strikeout extension and a fix was suggested in ticket #85 , in [this comment][1].

This can probably be closed as duplicate...

[1]: https://github.com/timonwong/OmniMarkupPreviewer/issues/85#issuecomment-168078270
