### ISSUE TITLE
Preview a markdown reports 404

### ISSUE THREAD

**Issue by victorwoo** [timonwong/OmniMarkupPreviewer#74]
When I use `ctrl`+`alt`+`o` to preview a markdown document, the browser shows:

    Error: 404 Not Found

    Sorry, the requested URL 'http://127.0.0.1:51004/view/28' caused an error:

    'buffer_id(28) is not valid (closed or unsupported file format)'

    **NOTE:** If you run multiple instances of Sublime Text, you may want to adjust
    the `server_port` option in order to get this plugin work again.

The logs in the console (`ctrl+\``) as flowing:

    OmniMarkupPreviewer: [INFO] Launching web browser for http://127.0.0.1:51004/view/28
    OmniMarkupPreviewer: [ERROR] Exception occured while rendering using MarkdownRenderer
      Traceback (most recent call last):
        File "D:\greensoft\Sublime Text 3 x32\Data\Packages\OmniMarkupPreviewer\OmniMarkupLib\RendererManager.py", line 266, in render_text
        rendered_text = renderer.render(text, filename=filename)
        File "D:\greensoft\Sublime Text 3 x32\Data\Packages\OmniMarkupPreviewer\OmniMarkupLib\Renderers/MarkdownRenderer.py", line 48, in render
        extensions=self.extensions)
        File "D:\greensoft\Sublime Text 3 x32\Data\Packages\OmniMarkupPreviewer\OmniMarkupLib\Renderers\libs\markdown\__init__.py", line 411, in markdown
        return md.convert(text)
        File "D:\greensoft\Sublime Text 3 x32\Data\Packages\OmniMarkupPreviewer\OmniMarkupLib\Renderers\libs\markdown\__init__.py", line 295, in convert
        newRoot = treeprocessor.run(root)
        File "D:\greensoft\Sublime Text 3 x32\Data\Packages\OmniMarkupPreviewer\OmniMarkupLib\Renderers\libs\markdown\extensions\codehilite.py", line 215, in run
        placeholder = self.markdown.htmlStash.store(code.hilite(),
        File "D:\greensoft\Sublime Text 3 x32\Data\Packages\OmniMarkupPreviewer\OmniMarkupLib\Renderers\libs\markdown\extensions\codehilite.py", line 109, in hilite
        lexer = get_lexer_by_name(self.lang)
        File "D:\greensoft\Sublime Text 3 x32\Data\Installed Packages\Evernote.sublime-package\lib\pygments\lexers\__init__.py", line 87, in get_lexer_by_name
        if _alias.lower() in aliases:
      AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by timonwong** [comment]
See #69 

The pygments package which EverNote is now using need to be updated in order to fix that.

**Comment by victorwoo** [comment]
How could a final user deal with this problem?

**Comment by naifan** [comment]
I face the same issues and I do not have EverNote.  I use one instance.

```
Error: 404 Not Found

Sorry, the requested URL 'http://127.0.0.1:51004/view/32' caused an error:

'buffer_id(32) is not valid (closed or unsupported file format)'

**NOTE:** If you run multiple instances of Sublime Text, you may want to adjust
the `server_port` option in order to get this plugin work again.
```
