### ISSUE TITLE
No refresh after modification

### ISSUE THREAD

**Issue by crysisfair** [timonwong/OmniMarkupPreviewer#79]
Unless file is saved, the preview donot refresh.

I use sublime text 2.0.2 x64 on win8.1 x64, browser is Google Chrome, the console writes:

> Traceback (most recent call last):
>  File ".\sublime_plugin.py", line 195, in on_modified
>    callback.**module**, "on_modified", FAST_EVENT_TIMEOUT)
>  File ".\sublime_plugin.py", line 154, in run_timed_function
>    ret = f()
>  File ".\sublime_plugin.py", line 194, in <lambda>
>    run_timed_function(lambda: callback.on_modified(v),
>  File ".\distraction_free_mode.py", line 23, in on_modified
>  File ".\distraction_free_mode.py", line 12, in on_distraction_free
> AttributeError: 'Window' object has no attribute 'settings'
> OmniMarkupPreviewer: [INFO] Launching web browser for http://127.0.0.1:51004/view/26

The network log of chrome is illustrated in this image:

![network log](https://cloud.githubusercontent.com/assets/9649279/8587532/e83b5464-262f-11e5-8812-c66aa7c8e714.png)

**Comment by timonwong** [comment]
The exception shows that it was thrown in `on_distraction_free` callback, which OmniMarkupPreviewer doesn't use at all. After search, I found following plugin use that:
- Markdown Editing (Which seems ST3 only now)

I suggest you disable that package and try again
