### ISSUE TITLE
OmniMarkupPreviewer 404

### ISSUE THREAD

**Issue by Kristinita** [timonwong/OmniMarkupPreviewer#93]
Hello, I established [OmniMarkupPreviewer](https://github.com/timonwong/OmniMarkupPreviewer). I open my page with Mediawiki markup and I press <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>o</kbd> to see it in my browser. But the mistake opened:

```
Error: 404 Not Found

Sorry, the requested URL 'http://127.0.0.1:51004/view/31' caused an error:

'buffer_id(31) is not valid (closed or unsupported file format)'

**NOTE:** If you run multiple instances of Sublime Text, you may want to adjust
the `server_port` option in order to get this plugin work again.
```

I tried to change «Settings - User» as advised [here](https://github.com/timonwong/OmniMarkupPreviewer/issues/82#issuecomment-158705946):

```
{
    "server_host": "0.0.0.0",
    "server_port": 9998
}
```

But the new mistake turned out:

```
Sorry, the requested URL 'http://127.0.0.1:9998/view/52' caused an error:

'buffer_id(52) is not valid (closed or unsupported file format)'

**NOTE:** If you run multiple instances of Sublime Text, you may want to adjust
the `server_port` option in order to get this plugin work again.
```

What I need to make for the correct work of OmniMarkupPreviewer? Thanks.

**Comment by jnns** [comment]
It's most likely a formatting error in your document. You should see if previewing another document (a very minimal example) works. 

If that's the case – or generally – have a look a the console output after issuing the preview command. It will display an error message like this: 

>   docutils.utils.SystemMessage: <string>:210: (SEVERE/4) Title level inconsistent

**Comment by Kristinita** [comment]
> It's most likely a formatting error in your document. You should see if previewing another document (a very minimal example) works.

I tried to preview the most simple documents with Mediawiki markup [for example](http://cyclowiki.org/wiki/%D0%A6%D0%B8%D0%BA%D0%BB%D0%BE%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F:%D0%A7%D0%B5%D1%80%D0%BD%D0%BE%D0%B2%D0%B8%D0%BA) and everywhere get the same error  :disappointed: .

> If that's the case – or generally – have a look a the console output after issuing the preview command. It will display an error message like this: 

During handling of the above exception, another exception occurred:

Output:

> Traceback (most recent call last):
>   File "C:\Documents and Settings\Admin.USER-AC59577756\Application Data\Sublime Text 3\Packages\OmniMarkupPreviewer\OmniMarkupLib\RendererManager.py", line 266, in render_text
>    rendered_text = renderer.render(text, filename=filename)
>   File "C:\Documents and Settings\Admin.USER-AC59577756\Application Data\Sublime Text 3\Packages\OmniMarkupPreviewer\OmniMarkupLib\Renderers\base_renderer.py", line 77, in render
>    text = self.executable_check(text, kwargs['filename'])
>    File "C:\Documents and Settings\Admin.USER-AC59577756\Application Data\Sublime Text 3\Packages\OmniMarkupPreviewer\OmniMarkupLib\Renderers\base_renderer.py", line 106, in executable_check
>    startupinfo=self.get_startupinfo())
>    File "./subprocess.py", line 824, in **init**
>    File "./subprocess.py", line 1118, in _execute_child
>    FileNotFoundError: [WinError 2] Не удается найти указанный файл

It may be, has a value that I use a Windows XP, edit files in Russian and my default browser is Pale Moon. Thanks.

**Comment by jfcherng** [comment]
https://github.com/timonwong/OmniMarkupPreviewer/issues/85

**Comment by tianleiyiji123** [comment]
Find the python-markdown sublime package.

On the Mac: subl "/Users/<username>/Library/Application Support/Sublime Text 3/Packages/OmniMarkupPreviewer/OmniMarkupLib/Renderers/libs/mdx_strikeout.py"

Replace the makeExtension() method with the following:

def makeExtension(*args, **kwargs):
    return StrikeoutExtension(*args, **kwargs)

Save, quit and reload Sublime Text.
