### ISSUE TITLE
Preview asciidoc file failed

### ISSUE THREAD

**Issue by buliaoyin** [timonwong/OmniMarkupPreviewer#96]
I'm using OmniMarkupPreviewer v3.0.0 in MacOSX, when I want to preview a asciidoc file, a blank page shown for me.

Add I had ruby and asciidoctor installed, and asciidoctor works fine in command line.
ruby version:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
asciidoctor version:
Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8) 

The console log:

```
OmniMarkupPreviewer: [INFO] Launching web browser for http://127.0.0.1:51004/view/29
b"/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- asciidoctor (LoadError)\n\tfrom /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'\n\tfrom /Users/le/Library/Application Support/Sublime Text 3/Packages/OmniMarkupPreviewer/OmniMarkupLib/Renderers/bin/asciidoc.rb:2:in `<main>'\n"
```

**Comment by passionlim** [comment]
You need to install asciidoctor ruby gem.

`sudo /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/gem install asciidoctor`

**Comment by ngr-t** [comment]
Just a remark, but I've got the same error despite asciidoctor is installed via homebrew. The problem is solved after I installed asciidoctor  via gem.
